alter table "public"."advertisers" drop constraint "advertisers_id_key";

alter table "public"."publishers" drop constraint "publishers_id_key";

alter table "public"."advertisers" drop constraint "advertisers_pkey";

alter table "public"."publishers" drop constraint "publishers_pkey";

drop index if exists "public"."advertisers_id_key";

drop index if exists "public"."advertisers_pkey";

drop index if exists "public"."publishers_id_key";

drop index if exists "public"."publishers_pkey";

create table "public"."ads" (
    "adId" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "networkId" bigint not null,
    "advertiserId" bigint not null,
    "content" json not null
);


create table "public"."campaigns" (
    "campaignId" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "advertiserId" bigint not null,
    "title" text,
    "budget" integer not null default 0,
    "cpmBid" integer not null default 0,
    "ads" bigint[],
    "networkId" bigint not null
);


create table "public"."clicks" (
    "clickId" bigint generated by default as identity not null,
    "timestamp" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "impressionId" bigint not null
);


alter table "public"."clicks" enable row level security;

create table "public"."impressions" (
    "impressionId" bigint generated by default as identity not null,
    "campaignId" bigint not null,
    "adId" bigint not null,
    "publisherId" bigint not null,
    "price" integer not null,
    "timestamp" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
);


create table "public"."networks" (
    "networkId" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "publisherId" bigint not null,
    "name" text default ''::text,
    "description" text,
    "adFormat" json not null
);


alter table "public"."advertisers" drop column "id";

alter table "public"."advertisers" add column "advertiserId" bigint generated by default as identity not null;

alter table "public"."advertisers" add column "name" text not null;

alter table "public"."advertisers" disable row level security;

alter table "public"."publishers" drop column "id";

alter table "public"."publishers" add column "name" text not null;

alter table "public"."publishers" add column "publisherId" bigint generated by default as identity not null;

alter table "public"."publishers" disable row level security;

CREATE UNIQUE INDEX "ads_adId_key" ON public.ads USING btree ("adId");

CREATE UNIQUE INDEX ads_pkey ON public.ads USING btree ("adId");

CREATE UNIQUE INDEX "campaigns_campaignId_key" ON public.campaigns USING btree ("campaignId");

CREATE UNIQUE INDEX campaigns_pkey ON public.campaigns USING btree ("campaignId");

CREATE UNIQUE INDEX clicks_pkey ON public.clicks USING btree ("clickId");

CREATE UNIQUE INDEX "impressions_impressionId_key" ON public.impressions USING btree ("impressionId");

CREATE UNIQUE INDEX impressions_pkey ON public.impressions USING btree ("impressionId");

CREATE UNIQUE INDEX "networks_networkId_key" ON public.networks USING btree ("networkId");

CREATE UNIQUE INDEX networks_pkey ON public.networks USING btree ("networkId");

CREATE UNIQUE INDEX advertisers_id_key ON public.advertisers USING btree ("advertiserId");

CREATE UNIQUE INDEX advertisers_pkey ON public.advertisers USING btree ("advertiserId");

CREATE UNIQUE INDEX publishers_id_key ON public.publishers USING btree ("publisherId");

CREATE UNIQUE INDEX publishers_pkey ON public.publishers USING btree ("publisherId");

alter table "public"."ads" add constraint "ads_pkey" PRIMARY KEY using index "ads_pkey";

alter table "public"."campaigns" add constraint "campaigns_pkey" PRIMARY KEY using index "campaigns_pkey";

alter table "public"."clicks" add constraint "clicks_pkey" PRIMARY KEY using index "clicks_pkey";

alter table "public"."impressions" add constraint "impressions_pkey" PRIMARY KEY using index "impressions_pkey";

alter table "public"."networks" add constraint "networks_pkey" PRIMARY KEY using index "networks_pkey";

alter table "public"."advertisers" add constraint "advertisers_pkey" PRIMARY KEY using index "advertisers_pkey";

alter table "public"."publishers" add constraint "publishers_pkey" PRIMARY KEY using index "publishers_pkey";

alter table "public"."ads" add constraint "ads_adId_key" UNIQUE using index "ads_adId_key";

alter table "public"."ads" add constraint "ads_advertiserId_fkey" FOREIGN KEY ("advertiserId") REFERENCES advertisers("advertiserId") ON DELETE CASCADE not valid;

alter table "public"."ads" validate constraint "ads_advertiserId_fkey";

alter table "public"."ads" add constraint "ads_networkId_fkey" FOREIGN KEY ("networkId") REFERENCES networks("networkId") ON DELETE CASCADE not valid;

alter table "public"."ads" validate constraint "ads_networkId_fkey";

alter table "public"."campaigns" add constraint "campaigns_advertiserId_fkey" FOREIGN KEY ("advertiserId") REFERENCES advertisers("advertiserId") ON DELETE CASCADE not valid;

alter table "public"."campaigns" validate constraint "campaigns_advertiserId_fkey";

alter table "public"."campaigns" add constraint "campaigns_campaignId_key" UNIQUE using index "campaigns_campaignId_key";

alter table "public"."campaigns" add constraint "campaigns_networkId_fkey" FOREIGN KEY ("networkId") REFERENCES networks("networkId") ON DELETE CASCADE not valid;

alter table "public"."campaigns" validate constraint "campaigns_networkId_fkey";

alter table "public"."clicks" add constraint "clicks_impressionId_fkey" FOREIGN KEY ("impressionId") REFERENCES impressions("impressionId") not valid;

alter table "public"."clicks" validate constraint "clicks_impressionId_fkey";

alter table "public"."impressions" add constraint "impressions_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES campaigns("campaignId") not valid;

alter table "public"."impressions" validate constraint "impressions_campaignId_fkey";

alter table "public"."impressions" add constraint "impressions_impressionId_key" UNIQUE using index "impressions_impressionId_key";

alter table "public"."impressions" add constraint "impressions_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES publishers("publisherId") not valid;

alter table "public"."impressions" validate constraint "impressions_publisherId_fkey";

alter table "public"."networks" add constraint "networks_networkId_key" UNIQUE using index "networks_networkId_key";

alter table "public"."networks" add constraint "networks_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES publishers("publisherId") ON DELETE CASCADE not valid;

alter table "public"."networks" validate constraint "networks_publisherId_fkey";

alter table "public"."advertisers" add constraint "advertisers_id_key" UNIQUE using index "advertisers_id_key";

alter table "public"."publishers" add constraint "publishers_id_key" UNIQUE using index "publishers_id_key";


